package model;

/**

 * This class is in charge of the gets and sets of both the sorter and the generator in addition to concatenating the values
 * generated in the arrays

 *@author: Nicolas Martinez  Cristian Molina  Juan Manuel Castillo.

 *@version: 23/08/2018/A

 */

public class Coprocessor {

	private Generator generator;
	private Sorter sorter;
	
	/**
	 * This method is responsible for initializing the generator and sorter in null.
	 */
	
	public Coprocessor()
	{
		generator = null;
		sorter = null;
	}

	public Generator getGenerator() {
		return generator;
	}

	public Sorter getSorter() {
		return sorter;
	}

	public void setGenerator(Generator generator) {
		this.generator = generator;
	}

	public void setSorter(Sorter sorter) {
		this.sorter = sorter;
	}
	
	/**
	 * This method is responsible for concatenating the values already generated by parameterizing an array.
	 * 
	 * @param arr of type array container of ints ready to be concatenated
	 * @return arreglo of type array
	 */
	
	public String concatenate(int[] arr)
	{
		String arreglo = "";
		for (int i = 0; i < arr.length; i++) {
			arreglo+=arr[i]+"-";
		}
		return arreglo;
	}
}
